# Generated by Django 4.2.6 on 2023-11-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='data_create',
        ),
        migrations.AddField(
            model_name='material',
            name='datetime_create',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
