# Generated by Django 4.2.6 on 2023-11-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_material_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(max_length=150, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='material',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
