# Generated by Django 4.2.6 on 2023-11-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_material_is_published_alter_material_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(max_length=150, verbose_name='slug'),
        ),
    ]
