# Generated by Django 4.2.6 on 2023-10-30 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(max_length=50, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='категория'),
        ),
    ]
