# Generated by Django 4.2.6 on 2023-10-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_datetime_changes_product_datetime_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_product',
        ),
    ]
