# Generated by Django 4.2.6 on 2023-10-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
