# Generated by Django 4.2.6 on 2023-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_product',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='название'),
        ),
    ]
