# Generated by Django 4.2.6 on 2023-11-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_version', models.IntegerField(verbose_name='Номер версии')),
                ('name_version', models.CharField(default='<django.db.models.fields.related.ForeignKey> - <django.db.models.fields.IntegerField>', verbose_name='Название версии')),
                ('is_active_version', models.BooleanField(default=False, verbose_name='Активность')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='продукт')),
            ],
        ),
    ]
