# Generated by Django 4.2.6 on 2023-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_published_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
